Updated input files for shock tests to run regression tests.  This required adding 2D/3D input files for Sod test.  Also updated regression test script so that it now runs shock tests.

diff --git a/tst/regression/test-algorithms b/tst/regression/test-algorithms
--- a/tst/regression/test-algorithms
+++ b/tst/regression/test-algorithms
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Script for running core regression tests
 #
-# There are 3 sets of core tests that are run in succession.
+# There are 5 sets of core tests that are run in succession.
 #
 # The FIRST consists of checking error in linear waves for each combination of
 #   CTU/VL integrator 
@@ -23,16 +23,30 @@
 #   hydro/mhd
 #   isothermal/adiabatic EOS
 # All use the 1D CTU integrator.  
-# The HLLC/HLLD tests use order=2,2p,3,3p reconstruction.
+# The HLLE tests use order=2,2p,3,3p reconstruction, the rest order=3.
+#
+# The FOURTH consists of checking error in circularly polarized Alfven waves
+# (CPAW) with different integrators, orders, and fluxes
+#   CTU/VL integrator 
+#   2/2p/3/3p
+#   Roe/HLLE/HLLD/force
+#   isothermal/adiabatic EOS
+#   1D/2D/3D
+#
+# The FIFTH consists of checking error in Sod (hydro) and RJ2a (mhd) shocktube.
+# with different integrators, orders, and fluxes
+#   CTU/VL integrator 
+#   2/2p/3/3p
+#   Roe/HLLE/HLLD/force/exact/two-shock
+#   1D/2D/3D
 #
 # For each test, this script checks for a warning message printed to stdout
 # by the problem generator.  This happens when the L1 error in the solution
 # at the end time exceeds an analytic estimate computed in Userwork_after_loop
 
 RUN_OPTS="time/tlim=1.2 problem/vflow=0.3 job/maxout=0"
-
 CNT=0
-TOTAL=121
+TOTAL=162
 
 #====================== FIRST SET OF TESTS =====================
 # check 1D/2D/3D CTU and VL integrators using Roe and 3rd order
@@ -43,7 +57,6 @@ rm -f LinWave-errors.2.dat
 #-------------------- loop over integrators -----------------------
 for INT in ctu vl
 do
-
   if [ "$INT" == "vl" ]; then
     ORD="3p"
     CFL="time/cour_no=0.4"
@@ -59,13 +72,11 @@ do
 #-------------------- loop over EOS ------------------------------
     for EOS in isothermal adiabatic
     do
-
       cd ../..
       make clean > clean.log
       let CNT=CNT+1
 
 # configure code
-
       if ! configure --with-integrator=$INT --with-gas=$GAS --with-eos=$EOS --with-problem=linear_wave --with-order=$ORD --with-nscalars=1 --with-flux=roe &> config.log
       then
         echo "Configure for test $CNT failed"
@@ -73,7 +84,6 @@ do
       fi
 
 # compile code
-
       if ! make all &> make.log
       then
         echo "Compile for test $CNT failed"
@@ -88,13 +98,11 @@ do
         echo "Athena crashed on test $CNT"
         exit
       fi
-
       if grep -q "WARNING" athena.log
       then
         echo "Regression test $CNT failed"
         exit
       fi
-  
       echo "Passed $CNT of $TOTAL: 1D $EOS $GAS linear wave using $INT " 
 
 # run 2D test
@@ -109,7 +117,6 @@ do
         echo "Regression test $CNT failed"
         exit
       fi
-  
       echo "Passed $CNT of $TOTAL: 2D $EOS $GAS linear wave using $INT " 
 
 # run 3D test
@@ -124,10 +131,6 @@ do
         echo "Regression test $CNT failed"
         exit
       fi
-  
-      rm -f athena.log
-      rm -f athena
-
       echo "Passed $CNT of $TOTAL: 3D $EOS $GAS linear wave using $INT " 
 
     done
@@ -143,7 +146,6 @@ rm -f LinWave-errors.2.dat
 #-------------------- loop over integrators -----------------------
 for INT in ctu vl
 do
-
   if [ "$INT" == "vl" ]; then
     CFL="time/cour_no=0.4"
   else
@@ -155,7 +157,6 @@ do
 
   for ORD in 2 2p 3p
   do
-  
     if [ "$INT" == "vl" -a "$ORD" == "2" ]; then
       continue
     fi
@@ -170,13 +171,11 @@ do
 #-------------------- loop over EOS ------------------------------
       for EOS in isothermal adiabatic
       do
-
         cd ../..
         make clean > clean.log
         let CNT=CNT+1
 
 # configure code
-
         if ! configure --with-integrator=$INT --with-gas=$GAS --with-eos=$EOS --with-problem=linear_wave --with-order=$ORD --with-nscalars=1 --with-flux=roe &> config.log
         then
           echo "Configure for test $CNT failed"
@@ -184,7 +183,6 @@ do
         fi
 
 # compile code
-
         if ! make all &> make.log
         then
           echo "Compile for test $CNT failed"
@@ -199,16 +197,11 @@ do
           echo "Athena crashed on test $CNT"
           exit
         fi
-
         if grep -q "WARNING" athena.log
         then
           echo "Regression test $CNT failed"
           exit
         fi
-
-        rm -f athena.log
-        rm -f athena
-  
         echo "Passed $CNT of $TOTAL: 1D $EOS $GAS linear wave using $INT and order=$ORD " 
 
       done
@@ -227,11 +220,8 @@ for FLUX in hlle hllc hlld force exact two-shock
 do
 
 #----------------------- loop over order  -------------------------
-# Note CTU order=3 and VL order=3p were done in first set
-         
   for ORD in 2 2p 3 3p
   do
-
     if [ "$FLUX" != "hlle" -a  "$ORD" != "3" ]; then
       continue
     fi
@@ -239,7 +229,6 @@ do
 #-------------------- loop over gas type -----------------------
     for GAS in hydro mhd
     do 
-
       if [ "$FLUX" == "hllc" -a  "$GAS" == "mhd" ]; then
         continue
       fi
@@ -256,7 +245,6 @@ do
 #-------------------- loop over EOS ------------------------------
       for EOS in isothermal adiabatic
       do
-
         if [ "$FLUX" == "two-shock" -a  "$EOS" == "adiabatic" ]; then
           continue
         fi
@@ -266,7 +254,6 @@ do
         let CNT=CNT+1
 
 # configure code
-  
         if ! configure --with-integrator=ctu --with-gas=$GAS --with-eos=$EOS --with-problem=linear_wave --with-order=$ORD --with-nscalars=1 --with-flux=$FLUX &> config.log
         then
           echo "Configure for test $CNT failed"
@@ -274,7 +261,6 @@ do
         fi
 
 # compile code
-
         if ! make all &> make.log
         then
           echo "Compile for test $CNT failed"
@@ -289,16 +275,11 @@ do
           echo "Athena crashed on test $CNT"
           exit
         fi
-
         if grep -q "WARNING" athena.log
         then
           echo "Regression test $CNT failed"
           exit
         fi
-
-        rm -f athena.log
-        rm -f athena
-
         echo "Passed $CNT of $TOTAL: 1D $EOS $GAS linear wave using $FLUX and order=$ORD " 
 
       done
@@ -315,7 +296,6 @@ rm -f cpaw-errors.dat
 #-------------------- loop over integrators -----------------------
 for INT in ctu vl
 do
-
   if [ "$INT" == "vl" ]; then
     CFL="time/cour_no=0.4"
   else
@@ -325,7 +305,6 @@ do
 #-------------------- loop over order -----------------------
   for ORD in 2 2p 3 3p 
   do
-
     if [ "$INT" == "vl" -a "$ORD" == "2" ]; then
       continue
     fi
@@ -336,6 +315,272 @@ do
 #-------------------- loop over EOS ------------------------------
     for EOS in isothermal adiabatic
     do
+      cd ../..
+      make clean > clean.log
+      let CNT=CNT+1
+
+# configure code
+      if ! configure --with-integrator=$INT --with-gas=mhd --with-eos=$EOS --with-problem=cpaw --with-order=$ORD --with-flux=roe &> config.log
+      then
+        echo "Configure for test $CNT failed"
+        exit
+      fi
+
+# compile code
+      if ! make all &> make.log
+      then
+        echo "Compile for test $CNT failed"
+        exit
+      fi
+      rm -rf clean.log config.log make.log
+      cd tst/regression
+
+# run 1D test
+      if ! ../../bin/athena -i ../1D-mhd/athinput.cpaw1d $RUN_OPTS $CFL &> athena.log
+      then
+        echo "Athena crashed on test $CNT"
+        exit
+      fi
+      if grep -q "WARNING" athena.log
+      then
+        echo "Regression test $CNT failed"
+        exit
+      fi
+      echo "Passed $CNT of $TOTAL: 1D $EOS cpaw using $INT and order=$ORD" 
+
+# run 2D test
+      let CNT=CNT+1
+      if ! ../../bin/athena -i ../2D-mhd/athinput.cpaw2d $RUN_OPTS $CFL &> athena.log
+      then
+        echo "Athena crashed on test $CNT"
+        exit
+      fi
+      if grep -q "WARNING" athena.log
+      then
+        echo "Regression test $CNT failed"
+        exit
+      fi
+      echo "Passed $CNT of $TOTAL: 2D $EOS cpaw using $INT and order=$ORD" 
+
+# run 3D test
+      let CNT=CNT+1
+      if ! ../../bin/athena -i ../3D-mhd/athinput.cpaw3d $RUN_OPTS &> athena.log
+      then
+        echo "Athena crashed on test $CNT"
+        exit
+      fi
+      if grep -q "WARNING" athena.log
+      then
+        echo "Regression test $CNT failed"
+        exit
+      fi
+      echo "Passed $CNT of $TOTAL: 3D $EOS cpaw using $INT and order=$ORD" 
+
+    done
+  done
+done
+
+#----------------- Now test different fluxes in CPAW ----------------
+#--------------------- loop over fluxes -------------------------
+for FLUX in hlle hlld force
+do
+
+#-------------------- loop over order -----------------------
+  for ORD in 2 3
+  do
+
+    cd ../..
+    make clean > clean.log
+    let CNT=CNT+1
+
+# configure code
+    if ! configure --with-integrator=ctu --with-gas=mhd --with-eos=adiabatic --with-problem=cpaw --with-order=$ORD --with-flux=$FLUX &> config.log
+    then
+      echo "Configure for test $CNT failed"
+      exit
+    fi
+
+# compile code
+    if ! make all &> make.log
+    then
+      echo "Compile for test $CNT failed"
+      exit
+    fi
+    rm -rf clean.log config.log make.log
+    cd tst/regression
+
+# run 1D test
+    if ! ../../bin/athena -i ../1D-mhd/athinput.cpaw1d $RUN_OPTS &> athena.log
+    then
+      echo "Athena crashed on test $CNT"
+      exit
+    fi
+    if grep -q "WARNING" athena.log
+    then
+      echo "Regression test $CNT failed"
+      exit
+    fi
+    echo "Passed $CNT of $TOTAL: 1D $EOS cpaw using $FLUX and order=$ORD" 
+
+# run 2D test
+    let CNT=CNT+1
+    if ! ../../bin/athena -i ../2D-mhd/athinput.cpaw2d $RUN_OPTS &> athena.log
+    then
+      echo "Athena crashed on test $CNT"
+      exit
+    fi
+    if grep -q "WARNING" athena.log
+    then
+      echo "Regression test $CNT failed"
+      exit
+    fi
+    echo "Passed $CNT of $TOTAL: 2D $EOS cpaw using $FLUX and order=$ORD" 
+
+# run 3D test
+    let CNT=CNT+1
+    if ! ../../bin/athena -i ../3D-mhd/athinput.cpaw3d $RUN_OPTS &> athena.log
+    then
+      echo "Athena crashed on test $CNT"
+      exit
+    fi
+    if grep -q "WARNING" athena.log
+    then
+      echo "Regression test $CNT failed"
+      exit
+    fi
+    echo "Passed $CNT of $TOTAL: 3D $EOS cpaw using $FLUX and order=$ORD" 
+
+  done
+done
+
+#======================== FIFTH SET OF TESTS ======================
+# Sod and RJ2a shock tube tests
+
+RUN_OPTS="job/maxout=0 problem/error_test=1"
+rm -f shock-errors.dat
+
+#--- Start with 1D shocks run in different direction -------------
+#-------------------- loop over integrators -----------------------
+for INT in ctu vl
+do
+  if [ "$INT" == "vl" ]; then
+    CFL="time/cour_no=0.4"
+    ORD="3p"
+  else
+    CFL=""
+    ORD="3"
+  fi
+
+#-------------------- loop over gas type -----------------------
+  for GAS in hydro mhd
+  do
+    if [ "$GAS" == "hydro" ]; then
+      INPUTFILE="athinput.sod"
+    else
+      INPUTFILE="athinput.rj2a"
+    fi
+
+    cd ../..
+    make clean > clean.log
+    let CNT=CNT+1
+
+# configure code
+
+    if ! configure --with-integrator=$INT --with-gas=$GAS --with-eos=adiabatic --with-problem=shkset1d --with-nscalars=1 --with-order=$ORD --with-flux=roe &> config.log
+    then
+      echo "Configure for test $CNT failed"
+      exit
+    fi
+
+# compile code
+    if ! make all &> make.log
+    then
+      echo "Compile for test $CNT failed"
+      exit
+    fi
+    rm -rf clean.log config.log make.log
+    cd tst/regression
+
+# run 1D test (shock in 1-direction)
+    if ! ../../bin/athena -i ../1D-$GAS/$INPUTFILE $RUN_OPTS $CFL &> athena.log
+    then
+      echo "Athena crashed on test $CNT"
+      exit
+    fi
+
+    if grep -q "WARNING" athena.log
+    then
+      echo "Regression test $CNT failed"
+      exit
+    fi
+  
+    echo "Passed $CNT of $TOTAL: 1D $GAS shock in 1-dir using $INT" 
+
+# run 2D test
+    let CNT=CNT+1
+    if ! ../../bin/athena -i ../1D-$GAS/$INPUTFILE $RUN_OPTS $CFL problem/shk_dir=2 domain1/Nx1=4 domain1/Nx2=512 &> athena.log
+    then
+      echo "Athena crashed on test $CNT"
+      exit
+    fi
+    if grep -q "WARNING" athena.log
+    then
+      echo "Regression test $CNT failed"
+      exit
+    fi
+  
+    echo "Passed $CNT of $TOTAL: 1D $GAS shock in 2-dir using $INT" 
+
+# run 3D test
+    let CNT=CNT+1
+    if ! ../../bin/athena -i ../1D-$GAS/$INPUTFILE $RUN_OPTS time/cour_no=0.4 problem/shk_dir=3 domain1/Nx1=4 domain1/Nx2=4 domain1/Nx3=256 &> athena.log
+    then
+      echo "Athena crashed on test $CNT"
+      exit
+    fi
+    if grep -q "WARNING" athena.log
+    then
+      echo "Regression test $CNT failed"
+      exit
+    fi
+  
+    rm -f athena.log
+    rm -f athena
+
+    echo "Passed $CNT of $TOTAL: 1D $GAS shock in 3-dir using $INT" 
+
+  done
+done
+
+#----------- Now test different fluxes/orders with shocks ----------------
+#-------------------- loop over gas type -----------------------
+for GAS in mhd hydro
+do
+  if [ "$GAS" == "hydro" ]; then
+    INPUTFILE="athinput.sod"
+  else
+    INPUTFILE="athinput.rj2a"
+  fi
+
+#--------------------- loop over fluxes -------------------------
+  for FLUX in roe hlle hllc hlld force exact
+  do
+      if [ "$GAS" == "hydro" -a "$FLUX" == "hlld" ]; then
+        continue
+      fi
+      if [ "$GAS" == "mhd" -a "$FLUX" == "hllc" ]; then
+        continue
+      fi
+      if [ "$GAS" == "mhd" -a "$FLUX" == "exact" ]; then
+        continue
+      fi
+
+#-------------------- loop over order -----------------------
+    for ORD in 2 2p 3 3p
+    do
+      if [ "$FLUX" != "roe" -a "$FLUX" != "hlle" ] && [ "$ORD" != "3" ]; then
+        continue
+      fi
 
       cd ../..
       make clean > clean.log
@@ -343,7 +588,7 @@ do
 
 # configure code
 
-      if ! configure --with-integrator=$INT --with-gas=mhd --with-eos=$EOS --with-problem=cpaw --with-order=$ORD --with-flux=roe &> config.log
+      if ! configure --with-integrator=ctu --with-gas=$GAS --with-eos=adiabatic --with-problem=shkset1d --with-nscalars=1 --with-order=$ORD --with-flux=$FLUX &> config.log
       then
         echo "Configure for test $CNT failed"
         exit
@@ -359,8 +604,8 @@ do
       rm -rf clean.log config.log make.log
       cd tst/regression
 
-# run 1D test
-      if ! ../../bin/athena -i ../1D-mhd/athinput.cpaw1d $RUN_OPTS $CFL &> athena.log
+# run 1D test (shock in 1-direction)
+      if ! ../../bin/athena -i ../1D-$GAS/$INPUTFILE $RUN_OPTS &> athena.log
       then
         echo "Athena crashed on test $CNT"
         exit
@@ -372,126 +617,90 @@ do
         exit
       fi
   
-      echo "Passed $CNT of $TOTAL: 1D $EOS cpaw using $INT and order=$ORD" 
-
-# run 2D test
-      let CNT=CNT+1
-      if ! ../../bin/athena -i ../2D-mhd/athinput.cpaw2d $RUN_OPTS $CFL &> athena.log
-      then
-        echo "Athena crashed on test $CNT"
-        exit
-      fi
-      if grep -q "WARNING" athena.log
-      then
-        echo "Regression test $CNT failed"
-        exit
-      fi
-  
-      echo "Passed $CNT of $TOTAL: 2D $EOS cpaw using $INT and order=$ORD" 
-
-# run 3D test
-      let CNT=CNT+1
-      if ! ../../bin/athena -i ../3D-mhd/athinput.cpaw3d $RUN_OPTS &> athena.log
-      then
-        echo "Athena crashed on test $CNT"
-        exit
-      fi
-      if grep -q "WARNING" athena.log
-      then
-        echo "Regression test $CNT failed"
-        exit
-      fi
-  
-      rm -f athena.log
-      rm -f athena
-
-      echo "Passed $CNT of $TOTAL: 3D $EOS cpaw using $INT and order=$ORD" 
+      echo "Passed $CNT of $TOTAL: 1D $GAS shock using $FLUX and order=$ORD" 
 
     done
   done
 done
 
-#----------------- Now test different fluxes in CPAW ----------------
-
-rm -f cpaw-errors.dat
-
-#--------------------- loop over fluxes -------------------------
-for FLUX in hlle hlld force
+#------------------- Now test 2D/3D shocks ---------------------
+#-------------------- loop over problem -----------------------
+for PROBLEM in shkset2d shkset3d
 do
 
-#-------------------- loop over order -----------------------
-  for ORD in 2 3
-  do
+#-------------------- loop over integrators -----------------------
+  for INT in ctu vl
+  do  
+    if [ "$INT" == "vl" ]; then
+      CFL="time/cour_no=0.4"
+      ORD="3p"
+    else
+      CFL=""
+      ORD="3"
+    fi
 
-    cd ../..
-    make clean > clean.log
-    let CNT=CNT+1
+#-------------------- loop over gas type -----------------------
+    for GAS in mhd hydro
+    do
+      if [ "$GAS" == "hydro" ]; then
+        INPUTFILE="athinput.sod"
+      else
+        INPUTFILE="athinput.rj2a"
+      fi
+
+      cd ../..
+      make clean > clean.log
+      let CNT=CNT+1
 
 # configure code
 
-    if ! configure --with-integrator=ctu --with-gas=mhd --with-eos=adiabatic --with-problem=cpaw --with-order=$ORD --with-flux=$FLUX &> config.log
-    then
-      echo "Configure for test $CNT failed"
-      exit
-    fi
+      if ! configure --with-integrator=$INT --with-gas=$GAS --with-eos=adiabatic --with-problem=$PROBLEM --with-order=$ORD --with-flux=roe &> config.log
+      then
+        echo "Configure for test $CNT failed"
+        exit
+      fi
 
 # compile code
-
-    if ! make all &> make.log
-    then
-      echo "Compile for test $CNT failed"
-      exit
-    fi
-    rm -rf clean.log config.log make.log
-    cd tst/regression
-
-# run 1D test
-    if ! ../../bin/athena -i ../1D-mhd/athinput.cpaw1d $RUN_OPTS &> athena.log
-    then
-      echo "Athena crashed on test $CNT"
-      exit
-    fi
-
-    if grep -q "WARNING" athena.log
-    then
-      echo "Regression test $CNT failed"
-      exit
-    fi
-  
-    echo "Passed $CNT of $TOTAL: 1D $EOS cpaw using $FLUX and order=$ORD" 
+      if ! make all &> make.log
+      then
+        echo "Compile for test $CNT failed"
+        exit
+      fi
+      rm -rf clean.log config.log make.log
+      cd tst/regression
 
 # run 2D test
-    let CNT=CNT+1
-    if ! ../../bin/athena -i ../2D-mhd/athinput.cpaw2d $RUN_OPTS &> athena.log
-    then
-      echo "Athena crashed on test $CNT"
-      exit
-    fi
-    if grep -q "WARNING" athena.log
-    then
-      echo "Regression test $CNT failed"
-      exit
-    fi
-  
-    echo "Passed $CNT of $TOTAL: 2D $EOS cpaw using $FLUX and order=$ORD" 
+      if [ "$PROBLEM" == "shkset2d" ]; then
+        if ! ../../bin/athena -i ../2D-$GAS/$INPUTFILE $RUN_OPTS $CFL &> athena.log
+        then
+          echo "Athena crashed on test $CNT"
+          exit
+        fi
+
+        if grep -q "WARNING" athena.log
+        then
+          echo "Regression test $CNT failed"
+          exit
+        fi
+        echo "Passed $CNT of $TOTAL: 2D $GAS shock using $INT" 
+      fi
 
 # run 3D test
-    let CNT=CNT+1
-    if ! ../../bin/athena -i ../3D-mhd/athinput.cpaw3d $RUN_OPTS &> athena.log
-    then
-      echo "Athena crashed on test $CNT"
-      exit
-    fi
-    if grep -q "WARNING" athena.log
-    then
-      echo "Regression test $CNT failed"
-      exit
-    fi
-  
-    rm -f athena.log
-    rm -f athena
+      if [ "$PROBLEM" == "shkset3d" ]; then
+        if ! ../../bin/athena -i ../3D-$GAS/$INPUTFILE $RUN_OPTS &> athena.log
+        then
+          echo "Athena crashed on test $CNT"
+          exit
+        fi
 
-    echo "Passed $CNT of $TOTAL: 3D $EOS cpaw using $FLUX and order=$ORD" 
+        if grep -q "WARNING" athena.log
+        then
+          echo "Regression test $CNT failed"
+          exit
+        fi
+        echo "Passed $CNT of $TOTAL: 3D $GAS shock using $INT" 
+      fi
 
+    done
   done
 done
